services:
  - type: web
    name: aerovitals-backend
    env: docker
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.9
      - key: GROQ_API_KEY
        sync: false  # Set this in Render dashboard 